### ISSUE TITLE
api: use of uninitialized memory (missing zero terminator)

### ISSUE THREAD

**Issue by mingodad** [the-xlang/x#104]
### Description

While building/testing `jule` on linux and running it through `valgrind` a use of unitialized memory was found in https://github.com/julelang/jule/blob/e78123825611e734811c026211cdfd546dda2b11/api/env.hpp#L114 and this change seems to fix the problem :
```
        char result[PATH_MAX];
        const ssize_t count = readlink("/proc/self/exe", result, PATH_MAX);
        if (count != -1) {
            result[count] = '\0';
            return jule::Str(result);
        }
```
Here is what we see in `man 2 readlink` (**readlink() does not append a null byte to buf**):
```
DESCRIPTION
       readlink()  places  the  contents  of  the  symbolic link pathname in the buffer buf, which has size bufsiz.
       readlink() does not append a null byte to buf.  It will (silently) truncate the contents  (to  a  length  of
       bufsiz characters), in case the buffer is too small to hold all of the contents.
```

### Expected behavior

No error reported by `valgrind`.

### Additional information

Nothing.

**Comment by mertcandav** [comment]
Hi. Thanks for your effort.
I opened a PR for that. Can you confirm that this patch fixes the problem?

**Comment by mingodad** [comment]
On my machine with your changes shown here https://github.com/julelang/jule/pull/105/files `valgrind` reported  no errors.

**Comment by mertcandav** [comment]
Alright. I'll merge relevant PR and close this issue.
Thanks for your contribution.
