### ISSUE TITLE
parser: `else` condition after a newline gets skipped

### ISSUE THREAD

**Issue by lakshgupta** [the-xlang/x#108]
### Description

The `else` condition gets skipped in case it's written after a newline.  

### Expected behavior

Either the code executes the else condition or fails with an error.

### Current behavior

The `else` condition does not get executed.

### Additional information

Here is a small program to reproduce the issue:
```
fn main() {
    let a:bool = false
    if a == true {
        outln("True")
    }
    else {
        outln("False")
    }
}
```

**Comment by mertcandav** [comment]
This issue is fixed with commit [`f4b18b0`](https://github.com/julelang/jule/commit/f4b18b0a5c0cde71bba6aa2d5d263961256cfe65), thanks for your contribution.
