### ISSUE TITLE
other: add a PR template

### ISSUE THREAD

**Issue by Panquesito7** [the-xlang/x#11]
### Detailed description

Add a pull request template to the repository to let maintainers know of the change easier and more.

### Context

A pull request template will make it easier for the maintainers and PR creators as well to make sure they've done everything correctly and have added the required information.

### Possible implementation

Add a PR template to the repository.

**Comment by mertcandav** [comment]
Hi. This is a good proposal.
Would you like to contribute by opening PR on this issue?

**Comment by Panquesito7** [comment]
Sure. I'll be making a PR soon, thanks. :)
