### ISSUE TITLE
other: add a security policy

### ISSUE THREAD

**Issue by Panquesito7** [the-xlang/x#13]
### Detailed description

For security reasons, when a vulnerability is found in the code, it should be reported to the maintainers/administrators rather than making an issue on GitHub; otherwise, everything could be exposed. It might be dangerous as well.

More information at https://docs.github.com/es/code-security/getting-started/adding-a-security-policy-to-your-repository

### Context

In case a vulnerability in the code is found, the users can check the security policy to know how to report vulnerabilities properly.
This will also make it much easier for the maintainers as well for the users and the community using the code.

### Additional information

If you need any help implementing this, let me know. 🙂

**Comment by mertcandav** [comment]
I'm opened a PR about this.
Please take a look, the fork will be merged if it is also ok for you.
