### ISSUE TITLE
other: create a `.github` repository

### ISSUE THREAD

**Issue by Panquesito7** [the-xlang/x#16]
### Detailed description

With a `.github` repository, you can:

- Have a predefined issue, PR, and **funding** templates for all repositories. To avoid duplication, you can also have a Code of Conduct, contributing, and security policy. **Licenses will not take effect on the other repositories.**
  - This can be overridden if a particular repository has other templates.
- Make a customized profile for the organization just like with GitHub users ([example](https://github.com/EddieHubCommunity/.github/blob/main/profile/README.md).
- Include any links and information about Jule, as well as add images and add a `.github-private` for only the team members.

### Context

IMO, this would make the GitHub organization much more elegant as well as give users the option to quickly check what the project is about.

### Possible implementation

Add `.github` and `.github-private` repositories for organization customization.

### Additional information

If you need any help with this, feel free to contact me via Discord: Panquesito7#3723

**Comment by mertcandav** [comment]
Hi,
We don't want to have such a repository, at least not in our current opinion.
It is our preference for all repositories to have their own configuration independently.
Also having a README on the organization profile is something we don't want, we want to keep the organization profile simple.

Thanks for your contribution.

**Comment by Panquesito7** [comment]
> It is our preference for all repositories to have their own configuration independently.

That is possible as I specified. But if you want to re-use a few stuff such as the code of conduct or issue templates, you can use that.
But it's alright :) thank you.

**Comment by mertcandav** [comment]
For now, we do not apply it because we do not consider a general template.
We will remember your proposal when we change our mind.

Thank you again.

**Comment by mertcandav** [comment]
After 2 years, this proposal is now accepted.

We now have a `.github` repository, which currently includes a `README.md`. Although the rest of the proposal hasn't been implemented yet, it's now more likely that the remaining parts will be accepted in the future.

Thanks for this proposal.
