### ISSUE TITLE
other: unable to compile julec

### ISSUE THREAD

**Issue by ghost** [the-xlang/x#19]
### What would you like to share?

When I run this command:
`go build -o julec -v src/cmd/julec/main.go`

rather than building julec I get this error:

> src/cmd/julec/main.go:16:2: no required module provides package github.com/julelang/jule: go.mod file not found in current directory or any parent directory; see 'go help modules'
> src/cmd/julec/main.go:17:2: no required module provides package github.com/julelang/jule/build: go.mod file not found in current directory or any parent directory; see 'go help modules'
> src/cmd/julec/main.go:18:2: no required module provides package github.com/julelang/jule/cmd/julec/gen: go.mod file not found in current directory or any parent directory; see 'go help modules'
> src/cmd/julec/main.go:19:2: no required module provides package github.com/julelang/jule/lex: go.mod file not found in current directory or any parent directory; see 'go help modules'
> src/cmd/julec/main.go:20:2: no required module provides package github.com/julelang/jule/parser: go.mod file not found in current directory or any parent directory; see 'go help modules'

### Additional information

go version: go1.20.1 linux/amd64

**Comment by mertcandav** [comment]
Hi,
With the development of the project, this command became obsolete over time. Please go to the `src` directory and execute the command `go build -o julec -v cmd/julec/main.go` in your terminal to get the expected result.

I would like to point out that this wrong command will be removed from the relevant places and will be fixed.

Thanks for your contribution.
