### ISSUE TITLE
other: snake_case complete localization identifiers

### ISSUE THREAD

**Issue by therisy** [the-xlang/x#2]
https://github.com/jule-lang/jule/blob/main/localization/turkish.json#L121
https://github.com/jule-lang/jule/blob/main/localization/english.json#L22
https://github.com/jule-lang/jule/blob/main/localization/english.json#L23
https://github.com/jule-lang/jule/blob/main/localization/english.json#L24
https://github.com/jule-lang/jule/blob/main/localization/english.json#L25
https://github.com/jule-lang/jule/blob/main/localization/english.json#L87
https://github.com/jule-lang/jule/blob/main/localization/english.json#L50
https://github.com/jule-lang/jule/blob/main/localization/english.json#L59
https://github.com/jule-lang/jule/blob/main/localization/english.json#L67
https://github.com/jule-lang/jule/blob/main/localization/english.json#L68

it may be better to put the word underline instead of compound

# current code

```
"notimpl_trait_def": ...
```

# desired

```
"not_impl_trait_def": ...
```

**Comment by mertcandav** [comment]
It was actually a choice, but it seems more correct to do it the way you say.
Localization packs will be edited.

Thanks for your contribution.

**Comment by mertcandav** [comment]
Localization identifiers edited as snake_case.
See: 5565c8e
