### ISSUE TITLE
std/jule, julec: add documentation in the code

### ISSUE THREAD

**Issue by Panquesito7** [the-xlang/x#35]
### Detailed description

It'd be great if the whole JuleC codebase was documented so that people that contribute or are just trying to learn Jule and C++ find it easier to understand the code, thus, attracting more users and more potential contributions.

### Context

Adding documentation would help in a few ways. Here are some:

- People interested in contributing will understand the codebase easier, allowing them to contribute more.
- People learning Jule or C++ will learn even faster.
- The documented code might also help the current and **new maintainers** when using other functions.
- Having documented code is always good and also helps keep the code clean and up-to-date.

### Additional information

This is not something critical, and should probably be done once Jule is fairly stable and more popular.

**Comment by mertcandav** [comment]
I've added some more documentation comments to the code. But I don't find it necessary to explain all the code in detail. The code makes most things understandably readable with define identifiers and stuff. Where documentation is needed in the code will be identified and documented over time, it's a natural process of development, so no specific workflow will be created to make this.

Thanks for your contribution.
