### ISSUE TITLE
ci/cd: use the `setup-jule` action

### ISSUE THREAD

**Issue by Panquesito7** [the-xlang/x#36]
### Detailed description

The [`setup-jule`](https://github.com/Panquesito7/setup-jule) action builds and compiles JuleC having a variety of options, such as choosing the version you'd like, adding to PATH, and more. This will also reduce a lot of the code being run in the workflows, which will also speed up the process.

The action supports macOS/Darwin and Linux/Ubuntu for now.

### Context

This will help run the actions much faster as well as having more options to customize the installation and all tests in **one workflow file** (if desired).

**Comment by mertcandav** [comment]
Ok. Setup-Jule seems stable enough to be used in Jule's workflows after recent updates.
I will make a PR for this.
