### ISSUE TITLE
other: wrong link to the license in the readme

### ISSUE THREAD

**Issue by Panquesito7** [the-xlang/x#47]
### What would you like to share?

The `README.md` file is linking to the license link which is now invalid and leads to a 404 page.
This should be fixed immediately, even if there's a license file separated, it should be properly mentioned.

_Steps to contribute_

1. Fork the repository [here](https://github.com/julelang/jule/fork).
2. Create a new branch named `fix_license_link`.
3. Open the `README.md` file.
4. Go to the bottom of the file, and change the license link to `LICENSE` without anything else.
5. Commit and push your changes.
6. Create a [pull request](https://github.com/julelang/jule/fork) to compare your changes.
7. You're done now! 🎉 You just have to wait until the maintainers review and merge your PR.

If you need any help, let us know about it. 🙂

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by mertcandav** [comment]
Hi.

Fixed with bf43d9b

Thanks for your contribution.
