### ISSUE TITLE
julec: improve compiler error message

### ISSUE THREAD

**Issue by PrimaIVoid** [the-xlang/x#55]
### Description

I noticed in this example that the compiler prints the exact same error twice, i'm not sure about the reason, but seem redundant
```
let s1 = "mor"
let s2 = 'p'

let out_str = s1 + s2
outln(out_str)
```
```
error: str and u8 data-types are not compatible
  --> main.jule:8:18
  8 | let out_str = s1 + s2
    |                  ^

error: str and u8 data-types are not compatible
  --> main.jule:8:18
  8 | let out_str = s1 + s2
    |                  ^

=== 2 error generated ===
```

### Expected behavior

Only get the error once, or make the second error message more precise, identifying as first error:
```
s1 (str)
 ^
```

And as second error, pointing at:
```
s2 (u8)
 ^
```

### Additional information

Using JuleC v0.0.5

**Comment by mertcandav** [comment]
This is not expected behavior and is a known issue. The expected behavior is that the relevant error is documented only once. This issue will be addressed. Thanks.
