### ISSUE TITLE
runtime: make slice produce undefined values

### ISSUE THREAD

**Issue by PrimaIVoid** [the-xlang/x#58]
### Description

About slices in the manual:

> At the example above, the s variable is 20 sized slices and all elements initialized with default value.

```
    let slice = make([]int, 6)
    outln(slice)
    // [94373079838218 0 3618977862967900464 4121138026052596788 3546639923513079344 13618]
```

### Expected behavior

I was expecting `slice` to be filled with "default values" and since its type is explicit as: `Int` that is `0 (Zero)`, instead it seem to produce undefined - garbage data

### Additional information

julec version beta 0.0.6 @master

**Comment by mertcandav** [comment]
This is absolutely unexpected behavior.
I'll investigate this.

Thanks.
