### ISSUE TITLE
jule: foreach loop in string

### ISSUE THREAD

**Issue by lareii** [the-xlang/x#7]
when i transpile this jule code, i get the decimal value of the chars in the "test" string:
```
fn main() {
    let s = "test"
    for _, b in s {
        outln(b)
    }
}
```
```
// OUTPUT
116
101
115
116
```

is this expected behavior, because it doesn't l like that in the [docs](https://jule.dev/pages/docs.html?page=common-concepts-control-flow)?

**Comment by mertcandav** [comment]
Hi,

Jule strings are encoded in UTF-8 and these values are bytes of the string.
When you foreach loop a string, you iterate through its bytes.

You'll find that you get the same values ​​when you get a same string as a byte slice:
```
fn main() {
    let bytes = ([]byte)("test")
    outln(bytes)
}

// expected output: [116 101 115 116]
```
If you want to get a byte as a string, please cast it:
```
fn main() {
    let s = "test"
    for _, b in s {
        outln((str)(b))
    }
}
```
I think this example will give you the result you want.
If you want to see a byte or rune as a character, cast it to string.

The relevant part of the documentation seems to be stuck in an old JuleC build, it will be updated.
Thanks for your contribution.
