### ISSUE TITLE
other: about fixed width integers and PR #73

### ISSUE THREAD

**Issue by mertcandav** [the-xlang/x#75]
### What would you like to share?

The PR #73 causes build errors, therefore reverted.
This problem have to investigate.
If problem can solved, this PR will be implemented.

Also here is a few questions for the PR author @vil02:
- This changes can effect performance?
- This changes reduces or increases portability of code between compilers, operating systems, CPUs?

Relevant PRs:
- #73 
- #74

**Comment by vil02** [comment]
>     * This changes can effect performance?
No. 

>     * This changes reduces or increases portability of code between compilers, operating systems, CPUs?
It increases portability. The size of the _basic integer types_ is not fixed. For example the `long` is 64 bits in gcc and 32 bits in MSVC. Please have a look at these two examples:
- [`int` and `long` have different size in gcc](https://godbolt.org/z/MfPhqbhzY),
- [`int` and `long` have same size in MSVC](https://godbolt.org/z/aTeaYnv64).

As suggested [here](https://github.com/julelang/jule/pull/73#issuecomment-1922312580) - please try to [rerun the failed jobs](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#about-re-running-workflows-and-jobs).

**Comment by mertcandav** [comment]
I can rerun all failed jobs but it will not change anything I think. CI uses compiler that compiled-from-source via main branch of Jule. Probably your PR compiled because changes not merged to main. Therefore I need to investigate that and I did, as a result my local compiler generates compilation errors same as CI.

I removed explicit generics of `std::make_tuple`  to solve problem. Clang compiles successfully, but GCC generates errors such as not declared, for example `jule::I32 not declared, did you mean jule::F32`. Do you know why is GCC cannot compile?

I also tried with `typedef` instead of `using` keyword. Same result.

My GCC compile command is: `g++-13 --std=c++17 dist/ir.cpp`

**Comment by vil02** [comment]
I just realized that [`U32`](https://github.com/julelang/jule/blob/1474009b63cdcc871033de0dfed7e280508281a4/api/types.hpp#L32) has the same size as [`U64`](https://github.com/julelang/jule/blob/1474009b63cdcc871033de0dfed7e280508281a4/api/types.hpp#L33), so `U32`, `U64`, `Uint` and `std::size_t` are all the same. Therefore, #73 introduced some problems (because `U32` and `I32` _started_ to have 32 bits).

**Comment by mertcandav** [comment]
Alright. I solved problem. GCC generates error because I missed to include `<cstdint>` header.

I will push your changes.
Thanks for your contribution.
