### ISSUE TITLE
other: convert all issue templates to issue forms

### ISSUE THREAD

**Issue by Panquesito7** [the-xlang/x#8]
### Proposal

We should use the newly provided GitHub issue forms. These can prevent blank issues or issues without enough information.
We can mark fields as optional or required, making things much more efficient, IMO.

Check the official GitHub blog about this: https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

### Additional

I want to work on this. 🙂

**Comment by mertcandav** [comment]
Hi,

Thanks for your proposal, looks good.
It will be merged when you make your changes in your fork and open the PR.
Please add refer this issue to your PR.

**Comment by Panquesito7** [comment]
Thanks. I'll be making a PR soon.
